spring:
  resources:
    static-locations:  file:F:/project4/
  redisson:
    address: 127.0.0.1:6379
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
dubbo:
  application:
    name: gateway
    owner: cskaoyan
  registry:
    address: zookeeper://127.0.0.1:2181
    check: true
    group: dubbo-dev
    simplified: true
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
#    retry-times: 30
#    cycle-report: false
#    group: dubbo-dev
  scan:
    base-packages: com.cskaoyan.gateway
captchaFlag : false




