spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/mall/order/dal/persistence/*Mapper.xml"
  type-aliases-package: com.mall.order.dal.entitys
pagehelper:
  helper-dialect: mysql

